#:schema node_modules/wrangler/config-schema.json

name = "langchain-js-cloudflare-input-tracing"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "langchain-js-cloudflare-input-tracing"

[vars]
PANGEA_DOMAIN = "aws.us.pangea.cloud"
